### ISSUE TITLE
variogram r2 score

### ISSUE THREAD

**Issue by Marion-Nicco** [GeoStat-Framework/GSTools#105]
Hello,

I am trying to use the comparison of variogram models for a set of data in the same way that is presented in the GStools tutorials from Aug 2020. I downloaded the latest release of the package yet when I type the command :
prara, pcov, r2 = fit_model.fit_variogram (bin_center, gamma, return_r2 = True) 
I get the error "expected three outputs, got two".
When I go into the fit_variogram function there is no mention of r2 in the returns of the function.

Did I miss an update or was r2 an old feature that was taken off in the latest release ? 

Thank you for your help,

![image](https://user-images.githubusercontent.com/67931903/97370022-b4e2cc00-1873-11eb-9afa-ef3d14e56c6f.png)
![Capture](https://user-images.githubusercontent.com/67931903/97369974-9b418480-1873-11eb-87ef-1d7b198a752f.PNG)

**Comment by MuellerSeb** [comment]
This is the documentation for the development version. In order to use the latest dev-version use the follwing command (as described in the [documentation](https://geostat-framework.readthedocs.io/projects/gstools/en/stable/#pip)):
```bash
pip install git+git://github.com/GeoStat-Framework/GSTools.git@develop
```

The `r2` score will be added in the next release.

Cheers,
Sebastian

**Comment by Marion-Nicco** [comment]
Oh I missed that sorry,

Thanks for the clarification !

Cheers,
