### ISSUE TITLE
No documentation for older versions

### ISSUE THREAD

**Issue by LSchueler** [GeoStat-Framework/GSTools#173]
I just realised that the documentation for older versions of GSTools is not hosted on readthedocs (we only have stable and latest). This is pretty inconvenient if you rely on an older version (see #172).
Maybe we should start keeping the documentation for older versions. But that would also mean that we have to manually set the links in the readme's etc.

Any opinions?

**Comment by MuellerSeb** [comment]
I activated older versions on ReadTheDocs, which we can keep afterwards:
- https://geostat-framework.readthedocs.io/projects/gstools/en/v1.0.1
- https://geostat-framework.readthedocs.io/projects/gstools/en/v1.1.1
- https://geostat-framework.readthedocs.io/projects/gstools/en/v1.3.0

unfortunately `v1.2.1` is not building due to a conflict with the used version of matplotlib (we didn't anticipate backward compatibility issues with mpl)

**Comment by LSchueler** [comment]
Wow, that's a strong opinion :-D
Thank's for taking care about the issue.

More opinions wanted:
Should we link to the older documentations somewhere in the readme? - Otherwise they are really hard to find as the older README's only link to the latest docs.

**Comment by MuellerSeb** [comment]
I wouldn't link to older documentations. We could add a statement, that older doc could be found on readthedocs with the version selector.

To solve the `v1.2.1` problem, we could create another release for v1.2 fixing the matplotlib version for the documentation.

**Comment by MuellerSeb** [comment]
We can't do anything about this when staying with readthedocs. Another release for 1.2 just to change doc-deps is making no sence to me.
