### ISSUE TITLE
mode_no bigger than 50 creates error

### ISSUE THREAD

**Issue by mschlutow** [GeoStat-Framework/GSTools#372]
```
srf = gs.SRF(
      model,
      generator="Fourier",
      period=[5000, 5000],
      mode_no=mode_no,
      seed=1681903
)
```
When I set `mode_no` > X where X~50, I get 
```
/lib/python3.10/site-packages/gstools/field/generator.py:804: RuntimeWarning: invalid value encountered in sqrt
  self._spectrum_factor = np.sqrt(
```
And the output field is empty. For `mode_no` < X, I get meaningful GRFs.

**Comment by LSchueler** [comment]
Hi mschlutow,

could you show us a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)? Because I cannot reproduce your problem on my machine. With `mode_no = 500` I get a nicely looking field and with `mode_no = 5000` my computer is slowly running hot, but so far I didn't get any RuntimeWarnings.

**Comment by mschlutow** [comment]
Hi LSchueler,
I removed the `seed` and now it works.

**Comment by LSchueler** [comment]
Glad to hear, but still very peculiar behaviour...
