### ISSUE TITLE
Why are Travis/Appveyor always uploading wheels?

### ISSUE THREAD

**Issue by banesullivan** [GeoStat-Framework/GSTools#62]
The Travis and Appveyor scripts upload a built wheel on every build...

https://github.com/GeoStat-Framework/GSTools/blob/5326163d567a6ac0121ca75c007c2ae7d46564b7/.travis.yml#L123-L127

https://github.com/GeoStat-Framework/GSTools/blob/5326163d567a6ac0121ca75c007c2ae7d46564b7/appveyor.yml#L12

Why? This seems excessive and it will cause a failed build on PRs from any forks (see #57 and #59)

**Comment by MuellerSeb** [comment]
You need to make the PRs in the [develop](https://github.com/GeoStat-Framework/GSTools/tree/develop) branch, since the master branch only holds the latest release.

The ``.travis.yaml`` was updated in this branch:

https://github.com/GeoStat-Framework/GSTools/blob/4bde6a0ac6d124234c671ff469c5448440423d57/.travis.yml#L104

So the exact thing you described was already solved. ;-)

**Comment by LSchueler** [comment]
I just clarified from which branch to fork in the CONTRIBUTING.MD

**Comment by MuellerSeb** [comment]
@LSchueler : thx! :+1:
