### ISSUE TITLE
Add equal aspect ratio to plot utilities

### ISSUE THREAD

**Issue by zperzan** [GeoStat-Framework/GSTools#66]
The field plotting utilities are great. 

Would it be possible to add equal aspect ratio functionality to _plot_2d and _plot_3d? Does it make sense to make equal aspect ratio the default option by setting
```python
ax.set_aspect('equal')
```
for 2D plots?

**Comment by MuellerSeb** [comment]
You can easily achieve that, since ``ax`` is always returned:

```python
import gstools as gs
x = y = range(100)
model = gs.Gaussian(dim=2, var=1, len_scale=10)
srf = gs.SRF(model, seed=20170519)
srf.structured([x, y])
ax = srf.plot()
ax.set_aspect('equal')
```

![eq_ax](https://user-images.githubusercontent.com/19690642/73073311-686afa00-3eb7-11ea-9ff2-be67e23f6f62.png)

We didn't want to force the user with an equal aspect, since there are often meshes that are quite longish, so the plot would be just a thin line.

Hope that helps!
Cheers, Sebastian
