### ISSUE TITLE
Perform Local Kriging by specifying maximum number of nearest observations

### ISSUE THREAD

**Issue by jacobgrasmick** [GeoStat-Framework/GSTools#99]
I am searching for a way in GSTools to perform local kriging. Basically, I want to specify the maximum number of nearest observations used for the kriging estimation at any point. Similar to `nmax` in gstat R package: https://www.rdocumentation.org/packages/gstat/versions/2.0-6/topics/krige

Is this possible? When searching the thread, I saw issue #50 which is sort of related, but not exactly.

Thanks in advance!

**Comment by MuellerSeb** [comment]
Hey there!

This is a feature we want to outsource to PyKrige in the future. It is already provided there, by `n_closest_points`:
https://geostat-framework.readthedocs.io/projects/pykrige/en/stable/generated/pykrige.ok.OrdinaryKriging.html#pykrige.ok.OrdinaryKriging.execute

The interface to GSTools is quite minimal at the moment:
https://geostat-framework.readthedocs.io/projects/pykrige/en/stable/examples/gstools_covmodel.html#sphx-glr-examples-gstools-covmodel-py

You could try that ;-)

**Comment by jacobgrasmick** [comment]
Ahh, okay I follow you, thanks!

This leads me to two questions:

1. What is the motivation for outsourcing to PyKrige? I'm sure there is a backstory here and just curious...

2. This question belongs in the PyKrige repository, but I'll save opening another issue - why is n_closest_points call not available for Universal Kriging? Is there something fundamental to the theory that I am missing here? btw, if you want me to open a new issue in the PyKrige repository with this question, just let me know :)

**Comment by MuellerSeb** [comment]
@jacobgrasmick : PyKrige joined the GeoStat-Framework this year and we now have to carefully decide, what is done with which package. The Idea ATM is to tightly connect [PyKrige](https://github.com/GeoStat-Framework/PyKrige) to [scikit-learn](https://github.com/scikit-learn/scikit-learn) as discussed here: https://github.com/GeoStat-Framework/PyKrige/issues/143

Both, PyKrige and GSTools, have a `v2` Milestone. PyKrige should then reuse a lot of the functionality of GSTools to cut down the maintenance load.

Concerning your second question: Features of PyKrige were implemented over the years following user requests. So the nearest neighbor routines have been implemented for the simpler case of ordinary kriging. Another point is, that the "internal" drift of Universal kriging would be only estimated local for the nearest neighbors. But in general you are right, that this is a missing feature. Local kriging is one of the features that would be outsourced to PyKrige, since we want PyKrige to provide the more fancy routines for kriging.

Feel free to open an issue for local universal kriging in PyKrige ;-)

Cheers, Sebastian

**Comment by MuellerSeb** [comment]
@jacobgrasmick : Closing for now. Feel free to re-open.
